FORMAT: 1A

# CDIO 3 Server

# Group Authentication

Has all the methods associated with authenticating a user.

## Authenticate [/authentication]

### Authenticates the user [POST /authentication/login]
+ Request (application/json)

        {
            "userName": "Hans",
            "password": "password"
        }
+ Response 200 (application/json)
        {
            "message": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0VXNlciJ9.m_ap4_eXb0iIPNyyz0Da5PWNMd-dxw6miecHLKHxEczEWzugbNuvFN4n_Il1rTImSe7TKKo7EqxS_R2NteV_3w",
            "status": 200
        }

# Group Users 

## Self [/self]

### View the currently authenticated user [GET]

### Update the currently authenticated user [PATCH]

## Users [/users]

### Creates a new user [POST]


### Views all users [GET]



## User [/users/{user_id}]

+ Parameters
    + user_id (number, required) - ID of the user in form of an integer.
    
   
### View a users information [GET]

### Update a user [PATCH]

+ Response 204 (application/json)

### Reset users password [GET /users/{user_id}/reset-password]

`{id: 2, name: 'Wauw', job: 'Pharmasist'}`